package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

type cleanOpts struct {
	dryRun bool
	quiet  bool
}

func newCleanCmd() *cobra.Command {
	o := &cleanOpts{}
	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Remove generated HTML reports and JSON snapshots",
		Long: `Recursively remove .html and .json files that were generated by trep.
This inspects file contents to ensure only trep-generated files are removed.`,
		RunE: o.run,
	}
	f := cmd.Flags()
	f.BoolVar(&o.dryRun, "dry-run", false, "print files that would be removed without deleting them")
	f.BoolVarP(&o.quiet, "quiet", "q", false, "suppress output")
	return cmd
}

func (o *cleanOpts) run(_ *cobra.Command, args []string) error {
	removed := 0
	err := filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			// Skip hidden directories (like .git)
			if strings.HasPrefix(d.Name(), ".") && d.Name() != "." {
				return filepath.SkipDir
			}
			return nil
		}

		ext := filepath.Ext(path)
		if ext != ".html" && ext != ".json" && ext != ".sarif" {
			return nil
		}

		// Read up to first 4KB to identify trep fingerprints
		b, err := readFirstBytes(path, 4096)
		if err != nil {
			return nil
		}

		isTrep := false
		if ext == ".html" {
			isTrep = bytes.Contains(b, []byte("tree-map")) || 
				bytes.Contains(b, []byte(`color:var(--text-main)">trep</span>`)) ||
				bytes.Contains(b, []byte(`color:#0f172a">trep</span>`)) ||
				bytes.Contains(b, []byte(`<!-- ── Summary card ──`))
		} else if ext == ".json" {
			isTrep = bytes.Contains(b, []byte(`"generated_at"`)) &&
				(bytes.Contains(b, []byte(`"suites"`)) || bytes.Contains(b, []byte(`"branch_pct"`)))
		} else if ext == ".sarif" {
			isTrep = bytes.Contains(b, []byte(`"name": "trep"`))
		}

		if isTrep {
			if !o.quiet {
				if o.dryRun {
					fmt.Fprintf(os.Stderr, "would remove %s\n", path)
				} else {
					fmt.Fprintf(os.Stderr, "removing %s\n", path)
				}
			}
			if !o.dryRun {
				_ = os.Remove(path)
			}
			removed++
		}
		return nil
	})

	if err != nil {
		return err
	}

	if !o.quiet && removed == 0 {
		fmt.Fprintln(os.Stderr, "No trep reports found to clean.")
	} else if !o.quiet && removed > 0 {
		if o.dryRun {
			fmt.Fprintf(os.Stderr, "Found %d file(s) to remove.\n", removed)
		} else {
			fmt.Fprintf(os.Stderr, "Removed %d file(s).\n", removed)
		}
	}
	return nil
}

func readFirstBytes(path string, n int) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	buf := make([]byte, n)
	br, err := f.Read(buf)
	if err != nil && err != os.ErrClosed {
		return buf[:br], nil // Best effort
	}
	return buf[:br], nil
}
