# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trep < Formula
  desc "Convert test results and coverage data to rich self-contained HTML reports"
  homepage "https://github.com/Yanujz/trep"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yanujz/trep/releases/download/v0.1.0/trep_darwin_amd64.tar.gz"
      sha256 "3bd2ff525da64a7d42e0cc5a0f131fdf79e64d199eb9999f818cea651f70c453"

      define_method(:install) do
        bin.install "trep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yanujz/trep/releases/download/v0.1.0/trep_darwin_arm64.tar.gz"
      sha256 "8ed6f4461f0de34f89e3391d1660cf3aeed13854b69d447fb0f5adecdaf1cab0"

      define_method(:install) do
        bin.install "trep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yanujz/trep/releases/download/v0.1.0/trep_linux_amd64.tar.gz"
      sha256 "56121a6e584110601868702a29652134bada71391730882b4da4134e8a3cb9ff"
      define_method(:install) do
        bin.install "trep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yanujz/trep/releases/download/v0.1.0/trep_linux_arm64.tar.gz"
      sha256 "dba4ed0f0cdc524b480dce9cac16fc81f43533f7224bc0995d11a5ee30da1a95"
      define_method(:install) do
        bin.install "trep"
      end
    end
  end

  test do
    system "#{bin}/trep", "--version"
  end
end
