# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trep < Formula
  desc "Convert test results and coverage data to rich self-contained HTML reports"
  homepage "https://github.com/trep-dev/trep"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trep-dev/trep/releases/download/v0.2.0/trep_darwin_amd64.tar.gz"
      sha256 "4d67f36f46e5ef3c79205061df62e9d9c9caacd4c66699df24693880af837157"

      define_method(:install) do
        bin.install "trep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trep-dev/trep/releases/download/v0.2.0/trep_darwin_arm64.tar.gz"
      sha256 "f8c36cdd91fe399a0aecfc206f78267272ba6c6a3c8c0b1d0d63ea2450d250f1"

      define_method(:install) do
        bin.install "trep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trep-dev/trep/releases/download/v0.2.0/trep_linux_amd64.tar.gz"
      sha256 "d095dd9b1871abb66e22f832de2918c52037ccaaf236f21dd26a889641a23f1b"
      define_method(:install) do
        bin.install "trep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trep-dev/trep/releases/download/v0.2.0/trep_linux_arm64.tar.gz"
      sha256 "c3d2fc4cec960b3ad2a66ad8b45248c1cd329e3ace3c2be39e89438597adf3b4"
      define_method(:install) do
        bin.install "trep"
      end
    end
  end

  test do
    system "#{bin}/trep", "--version"
  end
end
